Added Evo 15m and 40m
Terabee/terabee_api pull request #4
Opened 2021-04-20 15:20 UTC by mapi-ng

2021-04-20 17:47 UTC, pptaszni commented
Hey guys, pay attention when copy-pasting code from other sensors, especially author name, copyright year, and sensor names in the outputs :)

2021-04-21 07:24 UTC, pl-kabaradjian requested changes
As @pptaszni  pointed out, there are a few changes to address.

2021-04-21 07:24 UTC, pl-kabaradjian commented on examples/ExampleReadEvo15m.cpp
> +    std::cout << "usage: ./ExampleReadEvo60 DEVICE_NAME" << std::endl;
Fix sensor name

2021-04-21 07:24 UTC, pl-kabaradjian commented on examples/ExampleReadEvo40m.cpp
> +    std::cout << "usage: ./ExampleReadEvo60 DEVICE_NAME" << std::endl;
Fix sensor name

2021-04-21 07:24 UTC, pl-kabaradjian commented on include/terabee/internal/teraranger/TerarangerEvo15m.hpp
> + */
Fix author and copyright year

2021-04-21 07:24 UTC, pl-kabaradjian commented on include/terabee/internal/teraranger/TerarangerBasicCommon.hpp
>   * @Copyright Terabee 2020
Fix copyright year

2021-04-21 07:24 UTC, pl-kabaradjian commented on include/terabee/ITerarangerEvo40m.hpp
> + */
Fix author and copyright year

2021-04-21 07:24 UTC, pl-kabaradjian commented on include/terabee/ITerarangerEvo15m.hpp
> + * @Copyright Terabee 2020
Fix author and copyright year

2021-04-21 07:24 UTC, pl-kabaradjian commented on examples/ExampleReadEvo15m.cpp
> + */
Fix author and copyright year

2021-04-21 07:24 UTC, pl-kabaradjian commented on examples/ExampleReadEvo40m.cpp
> + */
Fix author and copyright year

2021-04-21 07:24 UTC, pl-kabaradjian commented on src/teraranger/TerarangerEvo15m.cpp
> + */
Fix author and copyright year

2021-04-21 07:24 UTC, pl-kabaradjian commented on src/teraranger/TerarangerEvo40m.cpp
> + */
Fix author and copyright year

2021-04-21 07:55 UTC, mapi-ng commented
Thanks for feedback, see the recent changes.

2021-04-21 09:26 UTC, pl-kabaradjian approved these changes

2021-04-21 09:52 UTC, merged